# Hostname (and path) to the root
baseURL = "https://blog.samyamashita.com/"

# Site title.
title = "sam yamashita"

# Theme to use
theme = "blog-theme"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

# Use Google Analytics
# See: https://gohugo.io/templates/internal/#google-analytics
googleAnalytics = "UA-79191761-1"

# Enable Emoji emoticons support for page content;
enableEmoji   = true

# Enable .GitInfo object for each page
enableGitInfo = true

[Params]
Author = "Sam Yamashita"




