# Hostname (and path) to the root
baseURL = "https://blog.samyamashita.com/"

# Theme to use
theme = "cactus-plus"

title = "Logging"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

# Use Google Analytics
# See: https://gohugo.io/templates/internal/#google-analytics
googleAnalytics = "UA-79191761-1"

# Enable Emoji emoticons support for page content;
enableEmoji   = true

# Enable .GitInfo object for each page
enableGitInfo = true

[Params]
Author      = "Sam Yamashita"
bio         = "Retrospective analysis on what I learn in daily life."

enableRSS = true

enableSummary = false

enableGoogleAnalytics = true

enableTwitterCard = true

subscribe = "RSS"

copyright = "Sam Yamashita"

# show latest posts in single page
showLatestPosts = true

# Share
enableShare = true

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "font-awesome"

[social]
twitter-square = "https://www.twitter.com/sota0805"
github-square  = "https://www.github.com/sotayamashita"
