baseURL = "https://samyamashita.netlify.com/"
languageCode = "en-us"
title = "👋 Hi, there"
theme="cactus-plus"

[Params]
Author="Sam Yamashita"

twitter = "@sota0805"

enableTwitterCard=true

# Disable to show latest posts in single page
showLatestPosts=false

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "font-awesome"
