baseURL = "http://example.org/"
languageCode = "en-us"
title = "👋 Hi, there"
theme="cactus-plus"

[Params]
Author="Sam Yamashita"

twitter = "@sota0805"

enableTwitterCard=true

# Disable to show latest posts in single page
showLatestPosts=false

# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
iconFont = "font-awesome"

[Social]
twitter="https://www.twitter.com/sota0805"
github="https://www.github.com/sotayamashita"
linkedin="https://www.linkedin.com/in/sotayamashita/"
